---
title: "dockerfile yozish"
---

> Эта статья ещё не переведена на русский язык.
> Пожалуйста, прочитайте [версию на узбекском](/guides/konteyner/dockerfile-yozish) или помогите нам с переводом на [GitHub](https://github.com/ismoilovdevml/devops-journey).
