---
title: "dockerfile yozish"
---

> This article has not been translated to English yet.
> Please read the [Uzbek version](/guides/konteyner/dockerfile-yozish) or help us translate it on [GitHub](https://github.com/ismoilovdevml/devops-journey).
